/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package groupmobleapplication;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author Dennis
 */
public class FormLeaderboard extends javax.swing.JFrame {

    private Person person = new Person("default", 'u', 0);
    LeaderboardPerson[] population = new LeaderboardPerson[10];

    /**
     * Creates new form FormLeaderboard
     */
    public FormLeaderboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelMathsQuiz = new javax.swing.JLabel();
        buttonMainMenu = new javax.swing.JButton();
        labelFirst = new javax.swing.JLabel();
        labelSecond = new javax.swing.JLabel();
        labelThird = new javax.swing.JLabel();
        label4to10 = new javax.swing.JLabel();
        labelRendering = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        labelMathsQuiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/groupmobleapplication/logo.png"))); // NOI18N

        buttonMainMenu.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        buttonMainMenu.setText("Main Menu");
        buttonMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMainMenuActionPerformed(evt);
            }
        });

        labelFirst.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        labelFirst.setForeground(new java.awt.Color(255, 255, 0));
        labelFirst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFirst.setText("1st: ");

        labelSecond.setFont(new java.awt.Font("Calibri", 0, 28)); // NOI18N
        labelSecond.setForeground(new java.awt.Color(255, 255, 255));
        labelSecond.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSecond.setText("2nd: ");

        labelThird.setFont(new java.awt.Font("Calibri", 0, 26)); // NOI18N
        labelThird.setForeground(new java.awt.Color(255, 150, 0));
        labelThird.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelThird.setText("3rd:  ");

        label4to10.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        label4to10.setForeground(new java.awt.Color(255, 100, 100));
        label4to10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label4to10.setText("4-10: ");

        labelRendering.setFont(new java.awt.Font("Calibri", 0, 30)); // NOI18N
        labelRendering.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRendering.setText("!!!WAIT - RENDERING!!!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelSecond, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelFirst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelThird, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(label4to10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 101, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelMathsQuiz)
                                .addGap(84, 84, 84))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(buttonMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelRendering, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(labelMathsQuiz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSecond, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelThird, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label4to10, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38)
                .addComponent(labelRendering, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        getContentPane().setBackground(Color.darkGray);
        DBManager dbm = new DBManager();
        population = dbm.generateLeaderboard();

        String first = labelFirst.getText() + population[0].getUserName() + " " + population[0].getUserScore();
        labelFirst.setText(first);
        String second = labelSecond.getText() + population[1].getUserName() + " " + population[1].getUserScore();
        labelSecond.setText(second);
        String third = labelThird.getText() + population[2].getUserName() + " " + population[2].getUserScore();
        labelThird.setText(third);
        //This will be treating like HTML and formatting will persist with line breaks etc.
        String rest = "<html><pre>";
        for (int i = 3; i < 10; i++) {
            rest += (i+1) + "th: " + population[i].getUserName() + " " + population[i].getUserScore() + "\n";
        }
        rest += "</pre></html>";
        label4to10.setText(rest);
        //Set font back to erase <pre> HTML Formatting
        label4to10.setFont(new Font("Calibri", Font.PLAIN, 18));
        labelRendering.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void buttonMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMainMenuActionPerformed
        this.setVisible(false);
        //Main Menu jFrame
        FormGameMenu formGameMenu = new FormGameMenu();
        formGameMenu.setPerson(person);
        formGameMenu.setVisible(true);
    }//GEN-LAST:event_buttonMainMenuActionPerformed

    public void setPerson(Person aPerson) {
        person = aPerson;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLeaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLeaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLeaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLeaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLeaderboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonMainMenu;
    private javax.swing.JLabel label4to10;
    private javax.swing.JLabel labelFirst;
    private javax.swing.JLabel labelMathsQuiz;
    private javax.swing.JLabel labelRendering;
    private javax.swing.JLabel labelSecond;
    private javax.swing.JLabel labelThird;
    // End of variables declaration//GEN-END:variables
}
