/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package groupmobleapplication;

import java.util.Random;

/**
 *
 * @author Dennis
 */
public class FormPlay extends javax.swing.JFrame {

    private Random rand = new Random(); // rand.nextInt((max - min) + 1) + min;
    
    private int chosenDifficulty = 0;
    private final int numberOfQuestions = 10;
    private int progressBarVal = 10;
    private int questionNo = 0;
    private Score playerScore;
    private Person person;
    private Question[] questions = new Question[numberOfQuestions];

    /**
     * Creates new form FormPlay
     */
    public FormPlay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelMathsQuiz = new javax.swing.JLabel();
        labelQuestion = new javax.swing.JLabel();
        buttonAnswer1 = new javax.swing.JButton();
        buttonAnswer2 = new javax.swing.JButton();
        buttonAnswer3 = new javax.swing.JButton();
        buttonAnswer4 = new javax.swing.JButton();
        progressBarQuiz = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        labelMathsQuiz.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelMathsQuiz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMathsQuiz.setText("Maths Quiz");

        labelQuestion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelQuestion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelQuestion.setText("Question");

        buttonAnswer1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonAnswer1.setText("Answer1");
        buttonAnswer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAnswer1ActionPerformed(evt);
            }
        });

        buttonAnswer2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonAnswer2.setText("Answer2");
        buttonAnswer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAnswer2ActionPerformed(evt);
            }
        });

        buttonAnswer3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonAnswer3.setText("Answer3");
        buttonAnswer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAnswer3ActionPerformed(evt);
            }
        });

        buttonAnswer4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonAnswer4.setText("Answer4");
        buttonAnswer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAnswer4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(progressBarQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buttonAnswer1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(buttonAnswer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonAnswer3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonAnswer4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(143, 143, 143))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelMathsQuiz)
                        .addGap(148, 148, 148))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(progressBarQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(labelMathsQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(labelQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156)
                .addComponent(buttonAnswer1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(buttonAnswer2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(buttonAnswer3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(buttonAnswer4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAnswer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAnswer1ActionPerformed
        checkAnswer(buttonAnswer1.getText());
    }//GEN-LAST:event_buttonAnswer1ActionPerformed

    private void buttonAnswer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAnswer2ActionPerformed
        checkAnswer(buttonAnswer2.getText());
    }//GEN-LAST:event_buttonAnswer2ActionPerformed

    private void buttonAnswer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAnswer3ActionPerformed
        checkAnswer(buttonAnswer3.getText());
    }//GEN-LAST:event_buttonAnswer3ActionPerformed

    private void buttonAnswer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAnswer4ActionPerformed
        checkAnswer(buttonAnswer4.getText());
    }//GEN-LAST:event_buttonAnswer4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        playerScore = new Score(chosenDifficulty);
        progressBarQuiz.setValue(progressBarVal);

        for (int i = 0; i < numberOfQuestions; i++) {
            questions[i] = new Question(chosenDifficulty);
        }

        labelQuestion.setText(getQuestionTitle());
        setRandomButton();
        setChosenButton();
    }//GEN-LAST:event_formWindowOpened

    public void setDifficulty(int i) {
        chosenDifficulty = i;
    }

    public void setPerson(Person aPerson) {
        person = aPerson;
    }

    private String getQuestionTitle() {
        String theQuestion = "What is " + questions[questionNo].getQuestion() + " ?";
        return theQuestion;
    }

    private void setRandomButton() {
        int[] randAnswer = new int[4];
        for (int i = 0; i < 4; i++) {
            int randOperator = rand.nextInt((1 - 0) + 1) + 0; // Random Operator (Number between 0-1)
            int randNumber = 0;
            switch (randOperator) {
                case 0:
                    randNumber = rand.nextInt((20 - 1) + 1) + 1; // Random Number (Number between 15-1)
                    randAnswer[i] = (Integer.parseInt(questions[questionNo].getAnswer())) + randNumber;
                    break;
                case 1:
                    randNumber = rand.nextInt((20 - 1) + 1) + 1; // Random Number (Number between 15-1)
                    randAnswer[i] = (Integer.parseInt(questions[questionNo].getAnswer())) - randNumber;
                    break;
            }
        }
        buttonAnswer1.setText(Integer.toString(randAnswer[0]));
        buttonAnswer2.setText(Integer.toString(randAnswer[1]));
        buttonAnswer3.setText(Integer.toString(randAnswer[2]));
        buttonAnswer4.setText(Integer.toString(randAnswer[3]));
    }

    private void setChosenButton() {
        System.out.println((questionNo + 1));
        System.out.println("Answer is " + questions[questionNo].getAnswer());
        int buttonNumber = rand.nextInt((4 - 1) + 1) + 1;
        switch (buttonNumber) {
            case 1:
                buttonAnswer1.setText(questions[questionNo].getAnswer());
                break;
            case 2:
                buttonAnswer2.setText(questions[questionNo].getAnswer());
                break;
            case 3:
                buttonAnswer3.setText(questions[questionNo].getAnswer());
                break;
            case 4:
                buttonAnswer4.setText(questions[questionNo].getAnswer());
                break;
        }
    }

    private void checkAnswer(String buttonAnswer) {
        if (buttonAnswer.equals(questions[questionNo].getAnswer())) {
            System.out.println("Correct");
            playerScore.addPoints();
            System.out.println("User Score: " + playerScore.getScore());
            System.out.println(" ");
            advanceQuestion();
        } else {
            System.out.println("Incorrect");
            System.out.println(" ");
            advanceQuestion();
        }
    }

    private void advanceQuestion() {
        questionNo++;
        progressBarVal += 10;
        if (questionNo < 9) {
            progressBarQuiz.setValue(progressBarVal);
            labelQuestion.setText(getQuestionTitle());
            setRandomButton();
            setChosenButton();
        } else {
            System.out.println("Congrats");
            //New Congratulations(Showing Score) Frame
            this.setVisible(false);
            FormGameOver formGameOver = new FormGameOver();
            formGameOver.setPerson(person);
            formGameOver.setScore(playerScore);
            formGameOver.setVisible(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPlay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAnswer1;
    private javax.swing.JButton buttonAnswer2;
    private javax.swing.JButton buttonAnswer3;
    private javax.swing.JButton buttonAnswer4;
    private javax.swing.JLabel labelMathsQuiz;
    private javax.swing.JLabel labelQuestion;
    private javax.swing.JProgressBar progressBarQuiz;
    // End of variables declaration//GEN-END:variables
}
