/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package groupmobleapplication;

import java.awt.Color;
import java.awt.GridLayout;
import java.util.Arrays;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Dennis
 */
public class FormAdminCP extends javax.swing.JFrame {

    /**
     * Creates new form FormAdminCP
     */
    public FormAdminCP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelMathsQuiz = new javax.swing.JLabel();
        labelAdminCP = new javax.swing.JLabel();
        buttonPrintDB = new javax.swing.JButton();
        buttonAddAdmin = new javax.swing.JButton();
        buttonGetPassword = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        labelMathsQuiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/groupmobleapplication/logo.png"))); // NOI18N

        labelAdminCP.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        labelAdminCP.setForeground(new java.awt.Color(255, 255, 255));
        labelAdminCP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAdminCP.setText("Admin Control Panel");

        buttonPrintDB.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        buttonPrintDB.setText("printUserList");
        buttonPrintDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrintDBActionPerformed(evt);
            }
        });

        buttonAddAdmin.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        buttonAddAdmin.setText("addAdmin");
        buttonAddAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddAdminActionPerformed(evt);
            }
        });

        buttonGetPassword.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        buttonGetPassword.setText("getPassword");
        buttonGetPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGetPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelMathsQuiz)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buttonAddAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonGetPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(buttonPrintDB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(85, 85, 85))))
            .addComponent(labelAdminCP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(labelMathsQuiz)
                .addGap(18, 18, 18)
                .addComponent(labelAdminCP, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonPrintDB, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(buttonAddAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(buttonGetPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPrintDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrintDBActionPerformed
        DBManager dbm = new DBManager();
        dbm.adminReadDB();
        System.out.println("Finished Reading Database");
    }//GEN-LAST:event_buttonPrintDBActionPerformed

    private void buttonAddAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddAdminActionPerformed
        //Dialog
        JTextField adminUsername = new JTextField();
        JPasswordField adminPassword = new JPasswordField();
        JPasswordField adminPasswordConfirm = new JPasswordField();
        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.add(new JLabel("New Admin Username:"));
        panel.add(adminUsername);
        panel.add(new JLabel("New Admin Password:"));
        panel.add(adminPassword);
        panel.add(new JLabel("Confirm New Admin Password:"));
        panel.add(adminPasswordConfirm);
        int result = JOptionPane.showConfirmDialog(null, panel, "New Admin Registration",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            String userName = adminUsername.getText();
            char[] password = adminPassword.getPassword();
            char[] passwordConfirm = adminPasswordConfirm.getPassword();
            boolean confirmedUN = validateUserName(userName);
            if (!confirmedUN) {
                JOptionPane.showMessageDialog(this,
                        "Somebody already has this username.",
                        "Invalid Username",
                        JOptionPane.ERROR_MESSAGE);
                adminUsername.setText("");
            }
            boolean confirmedPW = validatePassword(password, passwordConfirm);
            if (confirmedPW && confirmedUN) {
                //SQL Insert
                DBManager dbm = new DBManager(userName, password);
                boolean success = dbm.registerAdmin();
                if (success) {
                    System.out.println("Registration Successful");
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Registration Failed.",
                            "Registration Failed",
                            JOptionPane.ERROR_MESSAGE);
                    System.out.println("Registration Failed");
                }
            }
        } else {
            System.out.println("Cancelled");
        }
    }//GEN-LAST:event_buttonAddAdminActionPerformed

    private void buttonGetPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGetPasswordActionPerformed
        //Dialog
        JTextField chosenUserName = new JTextField();
        JPanel panel = new JPanel(new GridLayout(0, 1));
        panel.add(new JLabel("Enter Username:"));
        panel.add(chosenUserName);
        int result = JOptionPane.showConfirmDialog(null, panel, "Forgotten Password",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            String userName = chosenUserName.getText();
            DBManager dbm = new DBManager(userName);
            JOptionPane.showMessageDialog(this, "Password is " + dbm.getPassword());
        } else {
            System.out.println("Cancelled");
        }
    }//GEN-LAST:event_buttonGetPasswordActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        getContentPane().setBackground(Color.darkGray);
    }//GEN-LAST:event_formWindowOpened

    private Boolean validateUserName(String username) {
        DBManager dbm = new DBManager(username);
        if (!dbm.validateName()) { //False - Username Exists
            return false;
        }
        return true;
    }

    private Boolean validatePassword(char[] password, char[] passwordConfirm) {
        if (!Arrays.equals(password, passwordConfirm)) {
            JOptionPane.showMessageDialog(this,
                    "Passwords don't match.",
                    "Invalid Password",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if ((password.length < 5) || (password.length == 0)) {
            JOptionPane.showMessageDialog(this,
                    "Password is less than 5 characters or blank.",
                    "Invalid Password",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAdminCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAdminCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAdminCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAdminCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAdminCP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddAdmin;
    private javax.swing.JButton buttonGetPassword;
    private javax.swing.JButton buttonPrintDB;
    private javax.swing.JLabel labelAdminCP;
    private javax.swing.JLabel labelMathsQuiz;
    // End of variables declaration//GEN-END:variables
}
